[package]
name = "rustnpp"
version = "1.3.1"
authors = ["ნიკა <nika.begiashvili@gmail.com>", "Charsi <charsi2011@gmail.com"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.*"
winapi = { version = "0.3.9", features = ["winuser"] }
lazy_static = "1.4.*"
